### ISSUE TITLE
Why did you do this

### ISSUE THREAD

**Issue by zmxhawrhbg** [DeltaFlush/karting#1]
why did you do this i'm being serious, i have an issue with the fact that it's a mess of several languages, please fix i'm dying of death oihlkrh

**Comment by zmxhawrhbg** [comment]
jon decided that php was a good language i'm done

**Comment by DeltaFlush** [comment]
it's ok to be bilingual you racist

**Comment by ennuo** [comment]
im a polyglot
which means im superior to you
so fuck you

**Comment by DeltaFlush** [comment]
>  so fuck you

fuck you too racist

**Comment by zmxhawrhbg** [comment]
我很恨你。你聼到了我嗎？

**Comment by DeltaFlush** [comment]
still a maintainable project

**Comment by zmxhawrhbg** [comment]
this is about as maintainable as editing a book on the german language while learning english, russian, korean, japanese, and the british accent

**Comment by ennuo** [comment]
Korea

**Comment by ennuo** [comment]
I shoulda died in Korea
