### ISSUE TITLE
What...?

### ISSUE THREAD

**Issue by ennuo** [DeltaFlush/karting#2]
I did not like this. It was offensive...

I recommend taking the following actions:

Navigate to the `Settings` tab in this repo:

![image](https://user-images.githubusercontent.com/43017997/63645141-b6d85a80-c6c5-11e9-8e5b-eb9fc47d1146.png)

Scroll down the page towards the `Danger Zone` section:

![image](https://user-images.githubusercontent.com/43017997/63645165-f43ce800-c6c5-11e9-9d08-7d799487cb0b.png)

Be sure to press the `Delete Repository` button.
Once you hit this button, this prompt should appear:
![image](https://user-images.githubusercontent.com/43017997/63645178-38c88380-c6c6-11e9-8627-ff8a86eb6965.png)
Be sure to type your repo's name (karting) into this box, and finalize this exercise by pressing the 
`I understand the consequences, delete this repository` button.

Thank you.

(Proofread by Mommy and Daddy)
Sent from my iPhone

**Comment by zmxhawrhbg** [comment]
Tell your mom and dad hello! I too agree with your issue posted, Kotlin and PHP is just too dangerous of a mix...

**Comment by DeltaFlush** [comment]
Fuck you

**Comment by zmxhawrhbg** [comment]
Will do, gladly.

**Comment by DeltaFlush** [comment]
daddy

**Comment by ennuo** [comment]
owo

**Comment by ennuo** [comment]
*rolls on belly*

**Comment by DeltaFlush** [comment]
suck my PHP cock

**Comment by Hopefullyidontgetbanned** [comment]
i recommend using your ideological protection goggles

**Comment by zmxhawrhbg** [comment]
😎

**Comment by ennuo** [comment]
What a gamer

**Comment by DeltaFlush** [comment]
it is a good idea for PHP to call Kotlin code on an Apache server.
have trouble? install both apache, php, java runtime and kt runtime

**Comment by Hopefullyidontgetbanned** [comment]
no

**Comment by ennuo** [comment]
fuck

**Comment by zmxhawrhbg** [comment]
What if I want to use an NGINX reverse proxy

**Comment by ennuo** [comment]
*Moderated*

**Comment by ennuo** [comment]
*Moderated*

**Comment by DeltaFlush** [comment]
*Moderated*

**Comment by ennuo** [comment]
*Moderated*

**Comment by zmxhawrhbg** [comment]
_Moderated_

**Comment by DeltaFlush** [comment]
T00 bad

**Comment by ennuo** [comment]
> _Moderated_

Fuck you

**Comment by Hopefullyidontgetbanned** [comment]
Moderated

**Comment by DeltaFlush** [comment]
let's not say that

**Comment by zmxhawrhbg** [comment]
> it is a good idea for PHP to call Kotlin code on an Apache server.

It is a good idea for Python to be called remotely using a PHP script that lets one input the data for running the Python command

**Comment by ennuo** [comment]
![image](https://cdn.discordapp.com/attachments/487293594164527115/610672984436506624/JPEG_20190812_231345.jpg)

**Comment by zmxhawrhbg** [comment]
Watch out, Sackboy's coming to eat you!
